language: android
sudo: required
jdk:
    - oraclejdk8

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    # - tools
    - platform-tools
    - extra-google-m2repository
    - extra-android-m2repository

    # The BuildTools version used by your project
    - build-tools-22.0.1

    # The SDK version used to compile your project
    - android-22
    - sys-img-armeabi-v7a-android-22

  licenses:
    - android-sdk-preview-license-.+
    - android-sdk-license-.+
    - google-gdk-license-.+

before_install:
    - mkdir "$ANDROID_HOME/licenses" || true
    - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
    - chmod +x gradlew
    - ./gradlew dependencies || true

script:

    - "./gradlew clean build connectedCheck -PdisablePreDex --stacktrace"